### PR TITLE
Python added to tutorials (vignettes)

### PR DESCRIPTION
**Pull request by martinbenes1996**

### CODE REVIEW

**Comment by eguidotti** [comment]
In the latest version of pandas you should be able to pass the url directly, something like

```py
import pandas as pd

url = "https://storage.covid19datahub.io/data-1.csv"
x = pd.read_csv(url)
```
Would you mind to check? Thanks

**Comment by martinbenes1996** [comment]
Tried. The server responded 403. It worked only with the added header.

**Comment by eguidotti** [comment]
Alright, maybe worth to put a link to this issue here? 
https://datascience.stackexchange.com/questions/49751/read-csv-file-directly-from-url-how-to-fix-a-403-forbidden-error

**Comment by eguidotti** [comment]
Great thanks!

**Pull request merged**
