### PR TITLE
Added Haiti lev.2 /Colombia lev.2-3

### PR DESCRIPTION
**Pull request by FedericoLG**
Hello, 

I'm pleased to participate in this project, please consider this as a first contribution.  Being also the first Github project I work on, and the first R project ever, extended feedback would be welcome on the code and on any other methodological aspects. 

I tried to synthetize the code but I am sure it can be improved ( I am pretty sure it would be possible to synthetise the code for columns construction through a function in Col.R). 

Currently, the functions work as long as data caching is commented out and "cache" argument is set to false. The only error refers then to "cachedata" being undefined. 

**Sources**
- Colombia: Ministerio de Salud y Protección Social de Colombia. - Real time
- Haiti: Humanitarian Data Exchange  - Real time
  
Thanks for the patience in reviewing.   

Federico

### CODE REVIEW

**Comment by martinbenes1996** [comment]
Thank you for your contribution, you made a great work! I just made a review and cleaned the code a bit.

**Comment by martinbenes1996** [comment]
There is still a bug. Warning is raised from covid19() on HTI, lvl 2 and COL lvl 2 and 3, maybe needs to be compared with current version of _covid19()._, the base fork is older. 

Because of that bug, fallback (no data error) does not work, NULL is simply returned.

@emanuele-guidotti do not merge yet, review 2 needs to be done.

**Comment by eguidotti** [comment]
Hello Federico and sorry for the late feedback. 
The project went under heavy development in the last days...

The code was already nice. I cleaned it a bit and you can find the changes here
https://github.com/covid19datahub/COVID19/pull/46/files
The code now takes advantage of some of the new function we implemented in the package. See [here](https://covid19datahub.io/reference/index.html)

We prepared a tutorial with better guidelines and more extensive feedback to help you contribute to the project. See [here](https://github.com/covid19datahub/COVID19/wiki/Add-a-new-data-source). 

For being your first Github/R project, congrats!

May I just ask you where the data for Haiti population come from? So I'll add to the data sources. 
Many thanks!

**Comment by FedericoLG** [comment]
Hello Emanuele, 
Thank you very much to you and Martin for the feedback and the new resources, no better way to learn.  I'll go through the new materials and search for new data.  As for Haiti's population data, it was added through Martin's review. 

I stay available, good luck with this project!

**Comment by eguidotti** [comment]
Glad to hear that :) 

Martin, can you please post the source for Haiti's population? Thanks!

**Comment by martinbenes1996** [comment]
Source for Haiti population: https://en.wikipedia.org/wiki/Departments_of_Haiti

But now when I look at it, I swapped populations of _Sud-Est_ and _Sud_.

**Comment by sim55649** [comment]
> Source for Haiti population: https://en.wikipedia.org/wiki/Departments_of_Haiti
> 
> But now when I look at it, I swapped populations of _Sud-Est_ and _Sud_.

ok i will fix it in the next commit together with the longitude and latitude data. thanks

**Comment by eguidotti** [comment]
Ok great!
@FedericoLG I'd need your email address to send you the badge for contributors :) If you don't want to share it publicly here, you can send me a private message on [Slack](https://join.slack.com/t/covid19datahub/shared_invite/zt-e921sryd-Sb97p~skvovQM6NuXFUNCw)

**Pull request merged**
