### PR TITLE
Latvia and Austria government sources added

### PR DESCRIPTION
**Pull request by martinbenes1996**

### CODE REVIEW

**Comment by martinbenes1996** [comment]
Sources for Austrian region file:
https://de.wikipedia.org/wiki/Geographie_%C3%96sterreichs#Bundesl%C3%A4nder
https://de.wikipedia.org/wiki/Mittelpunkt_%C3%96sterreichs

**Comment by eguidotti** [comment]
Many thanks for your work! I reviewed and I'm going to merge now.
Here my comments:

- `LAT` -> `LVA` (ISO code)
- I cleaned some code and improved caching
- No need for regex, there is only one item which is in range format
- please remove the call to the functions when submitting. They prevent to install the package
- Austria, are icu and hosp percentage values? Are absolute numers available as well?

Thank you for your collaboration!

**Comment by martinbenes1996** [comment]
I did not find it in the sources. I could compute the percentages on absolute numbers, but since the percentages are rounded, it would not be very accurate.

**Comment by eguidotti** [comment]
That would help yes! Are the data available to convert the percentage to absolute numbers?

**Pull request merged**
