### PR TITLE
Update BRA.csv

### PR DESCRIPTION
**Pull request by guilhermegfv**
# What type of PR is this?

Select all that apply: [ ] -> [x]

- [ ] R 
- [ ] other

## R

I confirm: 

- [ ] I followed the [tutorial](https://github.com/covid19datahub/COVID19/wiki/Add-a-new-data-source)
- [ ] I checked the format with the [`ds_check_format`](https://covid19datahub.io/reference/ds_check_format.html) function
- [ ] I double checked the data (e.g. coherent with google search)

## Additional comments

Insert additional comments here...

### CODE REVIEW

**Comment by eguidotti** [comment]
Hi @guilhermegfv, thanks for the pull request! Looks great. I just tested and it is all good. Before, merging can I ask you what source you used for the coordinates and population? So I can add it to the data source file. Thanks!

**Comment by eguidotti** [comment]
I only found 1 possible issue. Lines 329 (SETOR DE INDUSTRIA E ABASTECIMENTO) and 341 (BRASILIA) share the same data for the admin areas, coordinates and population: "DISTRITO FEDERAL","BRASILIA",-157795,-479297,3055149

**Comment by eguidotti** [comment]
Hi @guilhermegfv, I look forward to sending you the badge and adding to the [contributors on the website](https://covid19datahub.io/articles/contributors.html). I'll be able to do that as soon as the pull request is merged. Unfortunately, I found a problem with the coordinates. They seem to be broken, e.g. -203155 without any decimal. Would it be possible for you to fix that? I think best choice would be to add the `codigo_ibge`  column from [here](https://github.com/kelvins/Municipios-Brasileiros/blob/main/csv/municipios.csv) to the file you submitted in this pull request. Then I can take care of merging with the coordinates. Thanks a lot!

**Comment by guilhermegfv** [comment]
Hi @eguidotti ! Happy New Year! I finally fixed the coordinates problems and committed what I think should work. Sorry for the delay, was a very busy december and now managed to get back on this study. Let me know any issue or any idea with the brazilian data that I could contribute. Thanks!

**Comment by eguidotti** [comment]
Hi @guilhermegfv and Happy New Year! Thanks for the update. I replaced the commas with dots for the decimal numbers in latitude and longitude. It seems for ESPIRITO SANTO there are 76 cities out of 78. I found a typo for Anchieta that was attributed to another state. I fixed this and set ESPIRITO SANTO for Anchieta. We are now 77 cities out of 78. Are you able to spot the last one?

**Comment by guilhermegfv** [comment]
The last one is Boa Esperança! The id is _da8690de_. The state was also misinformed, don't know what happen... I can resend the information with these two corrections, how do you think its better?

**Comment by eguidotti** [comment]
Thanks! Just fixed the population info for Boa Esperança and merged. In a couple of hours the new data should be online.
Sent you the badge and added your contribution on the [website](https://covid19datahub.io/articles/contributors.html) (in a few hours).
Don't hesitate to let me know if you see something weird with the data in the near future.
Many thanks!

**Comment by guilhermegfv** [comment]
Hi @eguidotti! How are you? Hope everything ok with you and your family in these crazy times. I'm having trouble using the data we merged. Sorry again for my inexperience. I'm currently with two questions. One is that when I download the raw data from covid-19 data hub io, I can only see about 10 cities from Espirito Santo. I don't know if I'm checking at the right place the information. And when I try to make the covsirphy (collaborative code from git) read the data, it says "Espirito Santo" is not a known province and its unable to model the data specifically to this state. Any suggestions about this? Really appreciate your help throught my studies.

**Comment by eguidotti** [comment]
Hi @guilhermegfv, thanks for your message.
Actually everything seems to work for me. I can get 78 cities for Espirito Santo in R:
```R
x <- covid19("BRA", level = 3)
y <- x[x$administrative_area_level_2=="Espirito Santo",]
length(unique(y$id))
# [1] 78
```
I don't know why you are not able to get these data from `covsirphy`. Maybe you can open an issue at their repo:
https://github.com/lisphilar/covid19-sir

**Pull request merged**
