### PR TITLE
Add 3rd dose vaccination data

### PR DESCRIPTION
**Pull request by vzemlys**
Lithuania started booster vaccination. Changes reflect the data on third vaccine dose.

# What type of PR is this?

Select all that apply: [ ] -> [x]

- [x] R 
- [ ] other

## R

I confirm: 

- [ ] I followed the [tutorial](https://github.com/covid19datahub/COVID19/wiki/Add-a-new-data-source)
- [ ] I checked the format with the [`ds_check_format`](https://covid19datahub.io/reference/ds_check_format.html) function
- [ ] I double checked the data (e.g. coherent with google search)

## Additional comments

Minor patch to reflect changes with regard to 3rd dose of vaccine.

### CODE REVIEW

**Comment by vzemlys** [comment]
Total vaccine data calculations are wrong

**Comment by eguidotti** [comment]
Hi @vzemlys, it actually seems correct what you were doing. 
Can I ask you what do you mean by "total vaccine data calculations are wrong"?
I have just updated the file [here](https://github.com/covid19datahub/COVID19/blob/master/R/ds_github.mpiktas.covid19lt.R)
Many thanks!

**Comment by vzemlys** [comment]
@eguidotti yes everything is correct. I had a moment of doubt looking at the official sources, but the doubt was dispelled :) Thanks for including this.

**Comment by eguidotti** [comment]
Thank you for the confirmation! This is very good to know

**Pull request closed without merging**
