### PR TITLE
Slovenia, utils::read_excel, South Africa

### PR DESCRIPTION
**Pull request by martinbenes1996**
Just implemented Slovenia at level 1 from datasource:
https://www.gov.si/en/topics/coronavirus-disease-covid-19/

The dataformat is _xlsx_, so I also implemented new utils parser for xlsx reading.

### CODE REVIEW

**Comment by martinbenes1996** [comment]
Slovenia has several administrative division systems, I added the statistical one.
https://en.wikipedia.org/wiki/Statistical_regions_of_Slovenia

I expect the for regional statistical data these will be used.

**Comment by martinbenes1996** [comment]
Just made the parser for _xlsx_ able to read specific sheet only or all sheets.

**Comment by martinbenes1996** [comment]
South African Republic added. (level 1, _confirmed_ at level 2 )
Source: https://github.com/dsfsi/covid19za

**Comment by martinbenes1996** [comment]
I added just very brief csv (TODO), coordinates are lat,lng of region capitals (rather centroids of regions?).
https://en.wikipedia.org/wiki/South_Africa#Administrative_divisions
https://en.wikipedia.org/wiki/List_of_South_African_provincial_capitals

**Comment by eguidotti** [comment]
I guess this can be closed. See #21 #20 #19

**Pull request closed without merging**
