### PR TITLE
Cze

### PR DESCRIPTION
**Pull request by martinbenes1996**
# What type of PR is this?

Select all that apply: [ ] -> [x]

- [x] R 
- [ ] other

## R

I confirm: 

- [x] I followed the [tutorial](https://github.com/covid19datahub/COVID19/wiki/Add-a-new-data-source)
- [x] I checked the format with the [`ds_check_format`](https://covid19datahub.io/reference/ds_check_format.html) function
- [x] I double checked the data (e.g. coherent with google search)

## Additional comments

ID for districts need to be added to *inst/extdata/db/CZE.csv*. I am not sure how to do it in the current version.

Due to IDs missing, it returns "no available data" for CZE, level 3. Need to be checked before merging.

### CODE REVIEW

**Comment by eguidotti** [comment]
Hi Martin, many thanks for it.
I fixed the csv. To generate or update a new csv you can use the [add_iso](https://covid19datahub.io/reference/add_iso.html) function.

Just one question before merging: we already had level 2 (only confirmed). It seems to me that now level 2 data are obtained aggregating level 3 data. I'm afraid that in this case we may have biased counts (e.g. if one city is not reporting we have lower counts for that region). I tried to compare the old counts for confirmed level 2 with the new ones obtained by aggregating level 3. The numbers are indeed a bit lower but seem very similar. What do you think? Can we aggregate the data from this source?

Thanks!

**Comment by martinbenes1996** [comment]
According to source description, the data comes from reports of regional hygienic stations, a local executive and monitoring organs of health and prevention. They are now responsible of the COVID-19 cases in areas that each manages.

There are 13 or 14 of them in Czechia. I would rather say that the COVID deaths are being a few days later after. I do not know who announce the death cause to the stations however, probably hospitals or some dissecting centers.

**Metadata of the source**: https://onemocneni-aktualne.mzcr.cz/api/v2/covid-19/umrti.csv-metadata.json
**Table of Hygienic stations**: https://www.mzcr.cz/Verejne/dokumenty/krajske-hygienicke-stanice_7735_1206_5.html

The best indicator to be sure is to check, whether the death numbers "converge" (get the same) after some time between now and the time. Is this valid?

**Comment by eguidotti** [comment]
Great, I double checked region by region and the difference with the previous data is very small. 
It seems a high quality dataset. For the citation, is the following correct? 
_"Ministery of Health of Czech Republic (2020), https://onemocneni-aktualne.mzcr.cz"_

**Comment by martinbenes1996** [comment]
Good. I would rather put this link, since the one is general. But yes, seems good otherwise.
https://onemocneni-aktualne.mzcr.cz/covid-19

**Comment by eguidotti** [comment]
Thank you! Updated

**Pull request merged**
